apiVersion: skaffold/v1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: gjani/laboschqpa-server
      context: laboschqpa.server
      docker:
        dockerfile: docker/Dockerfile-k8s_dev
    - image: gjani/laboschqpa-filehost
      context: laboschqpa.filehost
      docker:
        dockerfile: docker/Dockerfile-k8s_dev
    - image: szalkaikrisztian/laboschqpa-frontend
      context: laboschqpa.frontend
      docker:
        dockerfile: docker/Dockerfile-k8s_dev
deploy:
  kubectl:
   manifests:
     - laboschqpa.k8s/dev/*.yaml