apiVersion: skaffold/v1
kind: Config
build:
  local:
    push: false
  artifacts:
# If you want an image to be pulled from DockerHub instead of building it locally, comment out the corresponding artifact!
    - image: gjani/laboschqpa-server
      context: laboschqpa.server
      docker:
        dockerfile: docker/Dockerfile-k8s_dev
    - image: gjani/laboschqpa-filehost
      context: laboschqpa.filehost
      docker:
        dockerfile: docker/Dockerfile-k8s_dev
    - image: szalkaikrisztian/laboschqpa-frontend
      # TODO: Use the sync option to update files without rebuild the image: https://skaffold.dev/docs/pipeline-stages/filesync/
      context: laboschqpa.frontend
      docker:
        dockerfile: docker/Dockerfile-k8s_dev
deploy:
  kubectl:
   manifests:
     - laboschqpa.k8s/dev/*.yaml