apiVersion: skaffold/v1
kind: Config
build:
  local:
    push: false
  artifacts:
# If you want an image to be pulled from DockerHub instead of building it locally, comment out the corresponding artifact!
    - image: gjani/laboschqpa-server
      context: laboschqpa.server
      docker:
        dockerfile: docker/Dockerfile-k8s_dev
    - image: gjani/laboschqpa-filehost
      context: laboschqpa.filehost
      docker:
        dockerfile: docker/Dockerfile-k8s_dev
    - image: gjani/laboschqpa-imageconverter
      context: laboschqpa.imageconverter
      docker:
        dockerfile: docker/Dockerfile-k8s_dev
    - image: gjani/laboschqpa-client
      context: laboschqpa.client
      docker:
        dockerfile: docker/Dockerfile-k8s_dev
      sync:
        infer:
          - "src/**/*"
          - "public/**/*"
deploy:
  kubectl:
   manifests:
     - laboschqpa.k8s/dev/*.yaml